In [1]:
# Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
# elements using row and column indices as follows:

import numpy as np
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(f"Given array is : \n {arr}")
print('\n')
# a) Access 1st row, 2nd column

print(f'The element in 1st row, 2nd column is : {arr[0][1]}')
print('\n')

# b) Access 3rd row, 1st column

print(f'The element in 3rd row, 1st column is : {arr[2][0]}')
print('\n')

Given array is : 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


The element in 1st row, 2nd column is : 20


The element in 3rd row, 1st column is : 70




In [3]:
# Q.2 Questions on Basic NumPy Array:
# a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])

import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
print(f"Given Array : {arr}")
arr=arr[::-1]
print(f"Reverse of the array is : {arr}")
print("\n")



Given Array : [1 2 3 6 4 5]
Reverse of the array is : [5 4 6 3 2 1]




In [5]:

# b) Find the most frequent value and their indice(s) in the following arrays:
# i. x = np.array([1,2,3,4,5,1,2,1,1,1])

x = np.array([1,2,3,4,5,1,2,1,1,1])
print(f"Given Array : {x}")
unique_el,count=np.unique(x, return_counts=True)
print(f"The most frequent value is : {unique_el[np.argmax(count)]}")
indices= np.where(x==unique_el[np.argmax(count)])[0]
print(f"It occurs at indices {indices}")
print("\n")


Given Array : [1 2 3 4 5 1 2 1 1 1]
The most frequent value is : 1
It occurs at indices [0 5 7 8 9]




In [7]:


# ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
print(f"Given Array : {y}")
unique_el,count=np.unique(y, return_counts=True)
print(f"The most frequent value is : {unique_el[np.argmax(count)]}")
indices= np.where(y==unique_el[np.argmax(count)])[0]
print(f"It occurs at indices {indices}")



Given Array : [1 1 1 2 3 4 2 4 3 3]
The most frequent value is : 1
It occurs at indices [0 1 2]


In [9]:
#  Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
# operations like:

import numpy as np

a=np.array([1,2,3,4,5])
print("Original Array:")
print(a)
print('\n\n')



Original Array:
[1 2 3 4 5]





In [11]:
# a) Addition of 2 in all the element

print("Array after adding 2 to all elements:")
a=a+2
print(a)
print('\n\n')



Array after adding 2 to all elements:
[3 4 5 6 7]





In [13]:

# b) Multiply 3 with all the elements

print("Array after multiplying all elements by 3:")
a=a*3
print(a)
print('\n\n')


Array after multiplying all elements by 3:
[ 9 12 15 18 21]





In [15]:

# c) Divide every element by 2

print("Array after dividing all elements by 2:")
a=a/2
print(a)

Array after dividing all elements by 2:
[ 4.5  6.   7.5  9.  10.5]


In [17]:
# Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
# spaced 25 numbers from 10 to 100 using linspace(). 

import numpy as np

Your_Name=np.linspace(10,100,25)
print(f"Array formed is : \n {Your_Name}")
print('\n')


Array formed is : 
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]




In [19]:

# Print the dimensions of the array,shape, total elements, the data type of each element 
# and total number of bytes consumed by the array. 

print(f"Dimentions of the array is : {Your_Name.ndim}")
print('\n')

print(f"Shape of the array is : {Your_Name.shape}")
print('\n')

print(f"Size of the array is : {Your_Name.size}")
print('\n')

print(f"Datatype of each element of the array is : {Your_Name.dtype}")
print('\n')

print(f"Total number of bytes consumed by the array is : {Your_Name.nbytes}")
print('\n')


Dimentions of the array is : 1


Shape of the array is : (25,)


Size of the array is : 25


Datatype of each element of the array is : float64


Total number of bytes consumed by the array is : 200




In [21]:

# Find the transpose of this array using reshape() attribute. 

Your_Name_reshaped=Your_Name.reshape(25,1)
print(f"transpose of the array is : {Your_Name_reshaped}")
print('\n')


transpose of the array is : [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]




In [23]:

# Can we do the same with T attribute?

print(f"transpose of the array is : {Your_Name_reshaped.T}")
print('\n')


transpose of the array is : [[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]




In [25]:
# Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
# with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. 

import numpy as np

ucs420_yourname = np.array([
    [10, 20, 30, 40], 
    [50, 60, 70, 80], 
    [90, 15, 20, 35]
])
print(f"Original 2D Array (ucs420_yourname):\n{ucs420_yourname}\n")


Original 2D Array (ucs420_yourname):
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]



In [27]:

# Compute the mean,median, max, min, unique elements. 

print(f"Mean of array: {np.mean(ucs420_yourname)}\n")
print(f"Median of array: {np.median(ucs420_yourname)}\n")
print(f"Maximum value: {np.max(ucs420_yourname)}\n")
print(f"Minimum value: {np.min(ucs420_yourname)}\n")
print(f"Unique elements in the array: {np.unique(ucs420_yourname)}\n")


Mean of array: 43.333333333333336

Median of array: 37.5

Maximum value: 90

Minimum value: 10

Unique elements in the array: [10 15 20 30 35 40 50 60 70 80 90]



In [29]:

# Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. 

reshaped_ucs420_yourname = ucs420_yourname.reshape(4, 3)
print(f"Reshaped Array (4x3):\n{reshaped_ucs420_yourname}\n")


Reshaped Array (4x3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]



In [31]:

# Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>.

resized_ucs420_yourname = np.resize(ucs420_yourname, (2, 3))
print(f"Resized Array (2x3):\n{resized_ucs420_yourname}\n")

Resized Array (2x3):
[[10 20 30]
 [40 50 60]]

